### ISSUE TITLE
Add Cache-Control header in S3

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/tilecloud-chain#185]
See:
http://docs.pythonboto.org/en/latest/ref/s3.html#module-boto.s3.key
http://fr.wikipedia.org/wiki/Cache-Control#max-age

**Comment by pvalsecc** [comment]
Already implemented. Add a line like that in the S3 section of your YAML config (see README.rst):
```
cache_control: 'public, max-age=14400'
```

**Comment by sbrunner** [comment]
:-)
