### ISSUE TITLE
Doesn't work with Exoscale's S3 clone

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/tilecloud-chain#312]
We use a signature algo too modern for Exoscale. The work around is to add a $HOME/.aws/config with this content:
```
[default] 
s3 =  
   signature_version = s3
```

But would be cool if we could configure that in the YAML file.

**Comment by rbovard** [comment]
For the record the related error: https://github.com/camptocamp/c2cgeoportal/issues/2934#issuecomment-330810025

**Comment by rbovard** [comment]
Any plan to address this issue?

**Comment by sbrunner** [comment]
Actually no plane...

**Comment by rbovard** [comment]
Ok :(

Ping @yjacolin FYI

**Comment by retrack** [comment]
Exoscale will soon have v4 signature support which should fully address your issue.

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by yjacolin** [comment]
At this moment we should generate the tiles with a normal user (not www-data). This way boto3 will use .aws/config file to look up the correct configuration. We should add 
```
s3 =
  signature = s3
```
in the AWS config file.
