### ISSUE TITLE
WMTS Capabilities is not standard

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/tilecloud-chain#322]
The WMTSCapabilities shows empty ServiceIdentification and ServiceProvider which is not standard:
```
 <ows:ServiceIdentification> </ows:ServiceIdentification>
 <ows:ServiceProvider> </ows:ServiceProvider>
```
We should adapt this to either remove those line or fill mandatory content:

## ServiceIdentification
Mandatory tags with proposed default value:
* serviceType: Which URN to use?
* serviceTypeVersion: 1.1
* title:  (should be customized)

## ServiceProvider
* providerName: (should be customized)

https://github.com/camptocamp/tilecloud-chain/blob/master/tilecloud_chain/wmts_get_capabilities.jinja#L9-L10

**Comment by sbrunner** [comment]
What's the service type?
When I see that it meen for me that a WMTS capabilities is tor WMTS, not en elephant...

**Comment by sbrunner** [comment]
I don't know if its useful to have a default value for the title, it should be configurable, same for the descriptions, ans probably also some other fields...

**Comment by ponceta** [comment]
I do agree with this, but since we all are working a bit together, at least in Switzerland, we should agree on what is mandatory and what is not, regarding OGC standards.

Ping @procrastinatio @loicgasser

**Comment by ponceta** [comment]
@sbrunner regarding elephants https://github.com/opendatakit/sample-forms/blob/master/Elephant%20Death.xml

**Comment by yjacolin** [comment]
ServiceType is an URN, OGC Standard says:

> A service type URN from a registry of services, normally
> used for machine-to-machine communication

**Comment by yjacolin** [comment]
> I don't know if its useful to have a default value for the title, it should be configurable, same for the 
> descriptions, ans probably also some other fields...

* We should add mandatory fields in a clean way.
* We probably could add optional fields in a clean way

I updated the content for customized field.

**Comment by sbrunner** [comment]
Where is this service type is describe in the OGC specification?

**Comment by yjacolin** [comment]
Section 7.4.4 and 7.4.5 in OWS common standards in [06-121r9_OGC_Web_Services_Common_Standard.pdf](https://github.com/camptocamp/tilecloud-chain/files/1449801/06-121r9_OGC_Web_Services_Common_Standard.pdf)

**Comment by sbrunner** [comment]
on this document the example has the value:
`<ServiceType>urn:ogc:service:wms</ServiceType>`
on the wmts one and on chtopo we have:
`<ows:ServiceType>OGC WMTS</ows:ServiceType>`
Also in this document is written:
`The ServiceType shall comply to URNs in the ―service‖ category as specified in [OGC 09-046r1]. A specific OWS specification shall define a service type URN to be used by all implementing services.`
but in the document `OGC 09-046r1` there nothing useful about service.

Then for be it's unusable for machine communication, oups it was the initial goal :-P

**Comment by asaunier** [comment]
The WMTS capabilities used in OpenLayers examples also uses ``<ows:ServiceType>OGC WMTS</ows:ServiceType>``, see
https://openlayers.org/en/v4.5.0/examples/data/WMTSCapabilities.xml
